filter:
    excluded_paths: [tests/*]
checks:
    php:
        code_rating: true
        duplication: true
tools:
    external_code_coverage:
        timeout: 600
        runs: 3
    php_analyzer: true
    php_code_coverage: false
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: ['assets']
            files: ['./Alert.php']
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]